AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/migrate/*.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/Documentation:
  Exclude:
    - 'app/**/*'
    - 'config/**/*'
Lint/AmbiguousBlockAssociation:
  Excludes:
    - 'spec/controllers/items_controller_spec.rb'